options:
  log: true

variables:
  # constants
  CI_PROJECT_NAME: ci
  DOCKER_REPO: techdecaf
  CI_COMMIT_TAG: "{{EXEC `git describe --tags --always --dirty --abbrev=0`}}"
  CI_COMMIT_REF_NAME: "{{EXEC `git rev-parse --abbrev-ref HEAD`}}"
  CI_COMMIT_SHA: "{{EXEC `git rev-parse HEAD`}}"
  DOCKER_CURRENT_TAG: "{{.DOCKER_REPO}}/{{.CI_PROJECT_NAME}}:{{.CI_COMMIT_TAG}}"
  DOCKER_LATEST_TAG: "{{.DOCKER_CURRENT_TAG | replace .CI_COMMIT_TAG `latest`}}"

tasks:
  default:
    description: is the task that runs when no tasks have been specified.
    commands: [tasks list]

  build:
    description: build and tag docker project
    commands:
      - "docker build . --pull --tag {{.DOCKER_CURRENT_TAG}} --tag {{.DOCKER_LATEST_TAG}}"

  publish:
    description: publish to docker hub
    commands:
      - docker push {{.DOCKER_CURRENT_TAG}}
      - docker push {{.DOCKER_LATEST_TAG}}
