options:
  log: true

variables:
  # constants
  CI_PROJECT_NAME: ci
  DOCKER_REPO: techdecaf
  CI_COMMIT_TAG: "{{EXEC `git describe --tags --always --abbrev=0`}}"
  CI_COMMIT_REF_NAME: "{{EXEC `git rev-parse --abbrev-ref HEAD`}}"
  CI_COMMIT_SHA: "{{EXEC `git rev-parse HEAD`}}"
  LATEST_IMAGE: "{{.DOCKER_REPO}}/{{.CI_PROJECT_NAME}}:latest"
  VERSIONED_IMAGE: "{{.LATEST_IMAGE | replace `latest` .CI_COMMIT_TAG | replace `:v` `:`}}"

tasks:
  default:
    description: is the task that runs when no tasks have been specified.
    commands: [tasks list]

  login:
    description: login to docker hub
    variables:
      DOCKER_FILE: "{{.HOME}}/.docker/config.json"
    commands:
      - "{{if .DOCKER_CONFIG}}
        echo {{b64dec .DOCKER_CONFIG | WriteFile .DOCKER_FILE }}
        {{end}}"

  build:
    description: build and tag docker project
    commands:
      - "docker build . --pull --tag {{.LATEST_IMAGE}} --tag {{.VERSIONED_IMAGE}}"

  publish:
    description: publish to docker hub
    commands:
      - docker push {{.LATEST_IMAGE}}
      - docker push {{.VERSIONED_IMAGE}}

  release:
    description: bump version and release for deployment
    commands: [cgen bump --push]
